flags: {}
extra-package-dbs: []
packages:
- '.'
- location: lib/gdax-haskell
  extra-dep: true
- location:
    git: https://github.com/merijn/broadcast-chan.git
    commit: bab7ee9615ef741683b323d1d32c689b253567ea
  extra-dep: true
extra-deps:
- uuid-aeson-0.1.0.0
resolver: lts-8.24
