/* static data */
export const SET_CHANNELS = 'SET CHANNELS'
export const SET_PRODUCTS = 'SET PRODUCTS'
export const SET_REST_METHODS = 'SET REST METHODS'

/* dashboard */
export const SET_DASHBOARD_ACTIVE_TAB = 'SET DASHBOARD ACTIVE TAB'
export const SET_DASHBOARD_REST_METHOD = 'SET DASHBOARD REST METHOD'
export const SET_DASHBOARD_REST_ENDPOINT = 'SET DASHBOARD REST ENDPOINT'
export const SET_DASHBOARD_REST_PAYLOAD = 'SET DASHBOARD REST PAYLOAD'
export const ADD_DASHBOARD_REST_RECENT_ENDPOINT = 'ADD DASHBOARD REST RECENT ENDPOINT'

export const SET_DASHBOARD_STREAM_PRODUCTS = 'SET DASHBOARD STREAM PRODUCTS'
export const SET_DASHBOARD_STREAM_CHANNELS = 'SET DASHBOARD STREAM CHANNELS'

export const SET_DASHBOARD_DISPLAY_ERROR = 'SET DASHBOARD DISPLAY ERROR'
export const SET_DASHBOARD_DISPLAY_JSON = 'SET DASHBOARD DISPLAY JSON'
export const CLEAR_DASHBOARD_DISPLAY = 'CLEAR DASHBOARD DISPLAY'
